### ISSUE TITLE
I get an error 

### ISSUE THREAD

**Issue by carlgoodier** [dwave-examples/portfolio-optimization#25]
ValueError: API token not defined

**Comment by arcondello** [comment]
Hi @carlgoodier , you need to [configure access to Leap](https://docs.ocean.dwavesys.com/en/stable/overview/sapi.html) before you can submit problems to the hybrid solver or quantum computer.

**Comment by carlgoodier** [comment]
Thanks


Leap is not available to me…. I live in Thailand :(

**Comment by k8culver** [comment]
Closing as this is not a bug
